### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tomazbracic** [matehat/cqex#17]
Hi, 

I followed your readme. Added those two lines into config, and the just tried to start with client, but everything fall apart.

iex(1)> client = CQEx.Client.new!
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:cqerl_clusters, :"$primary_cluster")
             src/cqerl_cluster.erl:52: :cqerl_cluster.get_any_client/1
             lib/cqex/client.ex:17: CQEx.Client.new!/0
iex(1)> 

Any idea?

**Comment by matehat** [comment]
Have you made sure the cqex app is started?

``` elixir
Application.ensure_all_started :cqex
```

**Comment by tomazbracic** [comment]
```
➜  cassy mix deps.get
Running dependency resolution
All dependencies up to date
➜  cassy mix compile
Compiling 2 files (.ex)
warning: variable client is unused
  lib/cassy/conn.ex:3

Generated cassy app
➜  cassy iex -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Error while starting client {{"localhost:9042",9042},
                             [{keyspace,<<"mojKeyspace">>},
                              {cassandra_nodes,[<<"localhost:9042">>]},
                              {included_applications,[]}]} for cluster '$primary_cluster':
{shutdown,
    {failed_to_start_child,
        {cqerl_client,
            {{"localhost:9042",9042},
             [{cassandra_nodes,[<<"localhost:9042">>]},
              {included_applications,[]},
              {keyspace,mojKeyspace}]},
            1},
        {connection_error,nxdomain}}}Interactive Elixir (1.3.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> client = CQEx.Client.new!
** (CQEx.Error) :cluster_not_configured
    (cqex) lib/cqex/client.ex:17: CQEx.Client.new!/0
iex(1)> 
```

//
// I tried with IP, localhost, 127.0.0.1 and it doesn't work. I can connect using Datastax devcenter
//

### and app

``` elixir
iex(1)> Application.ensure_all_started :cqex
{:ok, []}
```

... any suggestion?

**Comment by matehat** [comment]
Are you sure the keyspace you use already exists in cassandra? "mojKeyspace"

**Comment by tomazbracic** [comment]
Hi, 

yes, keyspace already exists. It is there. I created it via DevCenter (Datastax) where I used "localhost", 9042 to connect. 

This is from my config/config.exs
config :cqerl,
   cassandra_nodes: ["127.0.0.1", "127.0.0.1"],  # read below
   keyspace: "mojKeyspace"

 # (above) I had here various options, ip:port x 2, ip:port 1x, without port, etc... none worked.

//
// Error that i get with this setup 
//
➜  cassy iex -S mix  
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Generated cassy app
Error while starting client {{{127,0,0,1},9042},
                             [{keyspace,<<"mojKeyspace">>},
                              {cassandra_nodes,
                                  [<<"127.0.0.1">>,<<"127.0.0.1">>]},
                              {included_applications,[]}]} for cluster '$primary_cluster':
shutdownInteractive Elixir (1.3.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

**Comment by matehat** [comment]
Can you try typing the config like this?

``` elixir
use Mix.Config

config :cqerl, 
  cassandra_nodes: [{"10.0.0.1", 9042}, {"10.0.0.2", 9042}],
  keyspace: "keyspace"
```

**Comment by matehat** [comment]
Also can you make sure you can connect to cassandra using cqlsh like this?

``` bash
$ cqlsh -k mojKeyspace 127.0.0.1 9042
```

**Comment by tomazbracic** [comment]
The above suggestion does not work. 

➜  cassy cqlsh -k mojKeyspace 127.0.0.1 9042
Connection error: ('Unable to connect to any servers', {'127.0.0.1': ProtocolError("cql_version '3.3.1' is not supported by remote (w/ native protocol). Supported versions: [u'3.4.2']",)})

Then according to this -> http://stackoverflow.com/questions/33002404/cassandra-cqlsh-unable-to-connect-to-any-servers
I did this below and I works like a charm. 

➜  cassy cqlsh -k mojKeyspace 127.0.0.1 9042 --cqlversion="3.4.2"
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.7 | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cqlsh:mojKeyspace>

**Comment by matehat** [comment]
In one of your prior comment above, you reported:

```
{shutdown,
    {failed_to_start_child,
        {cqerl_client,
            {{"localhost:9042",9042},
             [{cassandra_nodes,[<<"localhost:9042">>]},
              {included_applications,[]},
              {keyspace,mojKeyspace}]},
            1},
        {connection_error,nxdomain}}}
```

At the end you see the error that CQErl is reporting, `{connection_error,nxdomain}`, which according to [this website](http://erlang.org/pipermail/erlang-questions/2010-March/050349.html), indicates a connection configuration issue, most likely the host not resolving to something useful.

**Comment by matehat** [comment]
@tomazbracic did this help?
