### ISSUE TITLE
Shall I use the same client with multiple queries?

### ISSUE THREAD

**Issue by hopewise** [matehat/cqex#19]
Which is better? this example:

    def last_locations(conn, params) do
      user_ids= Poison.decode!(params["user_ids"])

      locations= user_ids
      |> Enum.map(&Task.async(fn -> last_location(&1) end))
      |> Enum.map(&Task.await/1)
      
      json(conn, locations)
    end
    
    defp last_location(user_id) do
        client = CQEx.Client.new!
        query= "SELECT * from myapp.latests WHERE user_id = #{user_id};"
        for [user_id: _, lat: lat, long: long, unix_time: unix_time] <- Q.call!(client, query) 
        |> Enum.to_list,
        do: [lat, long, unix_time]
    end

or this example: ? (where I am using one client for all queries)

    def last_locations(conn, params) do
      user_ids= Poison.decode!(params["user_ids"])
      client = CQEx.Client.new!
      locations= user_ids
      |> Enum.map(&Task.async(fn -> last_location(&1, client) end))
      |> Enum.map(&Task.await/1)
      
      json(conn, locations)
    end
    
    defp last_location(user_id, client) do
        
        query= "SELECT * from myapp.latests WHERE user_id = #{user_id};"
        for [user_id: _, lat: lat, long: long, unix_time: unix_time] <- Q.call!(client, query) 
        |> Enum.to_list,
        do: [lat, long, unix_time]
    end

**Comment by matehat** [comment]
The first one, each query should be done using a different client reference. Getting a client reference is really fast, doesn't introduces bottlenecks, and ensures proper load-balancing.

**Comment by hopewise** [comment]
Thanks for advice

**Comment by hopewise** [comment]
But what happen after getting the result of query? how would the client get disposed? or ex: terminating process?
