### ISSUE TITLE
Pool size and configuration

### ISSUE THREAD

**Issue by bvjebin** [matehat/cqex#2]
I keep getting the following error often:
**pool 'g2gDaARhf2EAYQBhAWIAACNSZAAJdW5kZWZpbmVk' failed to start member: {:error, {:connection_error, :econnrefused}}**

Does it have anything to do with pool size? If so, how to configure min and max pool size in cqex?

**Comment by matehat** [comment]
It doesn't have anything to do with pool size. So you say it doesn't happend always, but often. In what scenario does it happen?

**Comment by bvjebin** [comment]
I have no specific steps to reproduce this issue. I find this statement logged in the application error logs frequently. I suspect it happens before connection creation, again not 100% sure. The statement is printed from pooler which in turn is used by cqerl. 

To give you more information, I am using cassandra for a messaging application. There is frequent read and write operations to cassandra. The following snippet is the one I am using to create connection and execute queries.

```
try do
      client = CQEx.Client.new! credentials
      result = client |> Query.call!(qry)
      # client |> CQEx.Client.close
      {:ok, result}
    rescue
      exception ->
        Logger.error "Query Execution failed with exception #{inspect exception}"
        Logger.debug "Tried inserting data #{inspect qry}"
        Bugsnag.report exception
        {:error, exception}
    end
```

This block executes for every single query. 
_Note_: The connection close statement is commented believing that the created connections will be reused. 
Also is it correct to run **CQEx.Client.new! credentials** for every query? Will it reuse an existing connection from the pool? Or will it try to create connections and when it exceeds the default pool size, pooler throws the aforementioned error?

Is this the right way to do the database operation?

**Comment by matehat** [comment]
If you want a blocking implementation, it is the right way, but only if the Erlang process that runs this code is _transient_. If it is running inside a long-running process, you should close the connection after each _create, call_ cycle. `new` and `close` do not translate to direct connection opening and closing, but is rather a way for the library to load-balance queries across a pool of persistent connections. As the load increases, we add more connections, and each connections can serve **multiple** clients at the same time. 

The underlying pure Erlang library that does the heavy-lifting is where the client allocation. This is where the error you were having originates from. It _just_ got an update to the client allocation mechanism, so if you update to the latest, you may see your problem solved!

**Comment by bvjebin** [comment]
The latest update did the job. Not seeing this issue anymore. Thanks for your help.

**Comment by matehat** [comment]
Awesome!
