### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by peterRd** [matehat/cqex#27]
New to elixir and not sure whether this belongs in here but could be linked. I have created a test case where I am trying to connect to a remote cassandra instance however when I try to run it(via `mix test test/conn_test:10`), the escript.build or just a normal `mix deps.compile` it says the following: 
>** (Mix) Could not compile dependency :pooler, "/home/ubuntu/.mix/rebar3 bare compile --paths "/vagrant/test/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile pooler", update it with "mix deps.update pooler" or clean it with "mix deps.clean pooler"

Tried doing as suggested a compile, update and clean but to no avail. 

Some initial research pointed me to the TEST flag that gets defined and that tries to "export all functions" in pooler. If i manually go to the files mentioned and comment out the export  encapsulated in the TEST flag condition, it works fine. 

Any idea how to bypass this issue?

**Comment by peterRd** [comment]
Ok I solved this. Looks like it was to do with a version of erlang that was causing the problem. Was running on 20 changed it to use 19.3 and worked ok.

**Comment by cristafortuno** [comment]
Hi.

I am experiencing the same problem. I currently have Erlang 20 and Elixir 1.4.5. 
Would anyone know if there is other way aside from downgrading to Erlang 19.3? 
Elixir 1.4.5 is crashing in Erlang 19.3. :(

Thanks a lot!

**Comment by cristafortuno** [comment]
Oh, please ignore above. Issue is now fixed after changing dependency to {:cqex, "0.2.0"}. :)
