### ISSUE TITLE
Error while starting client

### ISSUE THREAD

**Issue by hopewise** [matehat/cqex#30]
When I start the phoenix server, I get this error:
```
Error while starting client {{"localhost",9042},
                             [{keyspace,<<"schools">>},
                              {cassandra_clusters,
                                  [{schools_cluster,
                                       {[{<<"localhost">>,9042}],
                                        [{keyspace,<<"schools">>}]}}]},
                              {included_applications,[]}]} for cluster schools_cluster:
shutdown
```

I can confirm that I can connect successfully to Cassandra using DBeaver client, or via cqlsh on terminal, as I have created the keyspace `schools`

the error above has no details, I just don't know what's the issue, any idea?

**Comment by matehat** [comment]
Can you indicate how you configured CQErl?

**Comment by hopewise** [comment]
here:
```
config :cqerl,
  cassandra_clusters: [

      schools_cluster:  { [{"localhost", 9042}], [keyspace: "schools"]   }
    ]
```
kindly notice, that it only worked at Mac, but when I tried to have the same setup at Ubuntu, it did not work, having the error above, although at Mac, I was using Docker, but at ubntu, I've installed Cassandra directly without docker..

**Comment by savoisn** [comment]
I have excatly the same problem
Any news?

**Comment by hopewise** [comment]
Not from my side.. I work on Mac now

**Comment by pragmatist-nz** [comment]
I faced the same issue, I resolved it by creating a keyspace in cqlsh, i.e.:

CREATE KEYSPACE dev  WITH REPLICATION = {     'class' : 'SimpleStrategy',     'replication_factor' : 1    };

The keyspace should match your settings in i.e. config/dev.exs
