### ISSUE TITLE
uuid library conflict

### ISSUE THREAD

**Issue by rranelli** [matehat/cqex#5]
(not sure if I should open this issue here or in the `cqerl` issue tracker...)

When I was starting to set up this library in my project I got the following
error when compiling my app:

```
> In mix.exs:
    {:uuid, ">= 1.1.3", [hex: :uuid]}

  > In deps/cqerl/rebar.config:
    {:uuid, ~r/.*/, [git: "https://github.com/okeuday/uuid.git", tag: "v1.4.1", manage
r: :rebar]}
```

I found out that the issue is because the `:uuid` dependencies **are not the
same**.

Hex's one is: https://github.com/zyro/elixir-uuid and the one `cqerl` depends on
is https://github.com/okeuday/uuid.

From what I understood, it is not possible to have two dependencies _with the
same name_.

In order to "fix" things for my project, I replaced my `uuid` entry in
`mix.exs`'s deps field with:

```
{:uuid, github: "okeuday/uuid", tag: "v1.4.1", manager: :rebar, override: true},
```

(I needed the `override: true` because `exq` depends on `elixir-uuid` as well).

I can't see a solution to this problem without changing the name of
`elixir-uuid` or `uuid`.

To work-around the issue, I then defined a module `UUID` in terms of `:uuid`:

```
defmodule UUID do
  # Terrible and ugly hack
  def uuid4 do
    :uuid.get_v4
    |> :uuid.uuid_to_string
    |> List.to_string
  end
end
```

**Comment by laibulle** [comment]
I have the same issue.

**Comment by matehat** [comment]
I don't know what to say .. Anyone else has suggestions? cqerl definitely can't start using https://github.com/zyro/elixir-uuid instead, as it's going to break for people using https://github.com/okeuday/uuid ...
