### ISSUE TITLE
`cqerl` is not listed as a dependency @ hex.pm

### ISSUE THREAD

**Issue by rranelli** [matehat/cqex#6]
`cqerl` is not listed as a dependency @ hex.pm: https://hex.pm/packages/cqex

Because of that, I need to explicitly add `cqerl` as a dependency of my application.

Is this correct??

**Comment by matehat** [comment]
It is correct. To not include it, I would have to add cqerl to hex.pm, but I can't because a couple of its dependencies are not available in hex.pm: semver and re2.
