### ISSUE TITLE
Argument error

### ISSUE THREAD

**Issue by schlan** [matehat/cqex#8]
Hi,

I have troubles connecting to my Cassandra cluster.

My configuration files looks like this:

```
use Mix.Config

config :cqerl, 
 cassandra_nodes: [ "192.168.99.100:9042", "192.168.99.100:9042" ],
 keyspace: "hevis"
```

After calling `client = CQEx.Client.new!`, I'm getting the following error message: 

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:cqerl_clusters, :"$primary_cluster")
             src/cqerl_cluster.erl:52: :cqerl_cluster.get_any_client/1
             lib/cqex/client.ex:17: CQEx.Client.new!/0
```

Any hints are very welcome :)
I fairly new to elixir, so hopefully I haven't missed an obvious step.

Thanks,
Seb

**Comment by schlan** [comment]
Never mind, fixed it.

**Comment by sebastian-nanek** [comment]
@schlan What's the solution?

**Comment by schlan** [comment]
@sebastian-nanek I had to add `:cqerl` to the list of applications and I got the keyspace wrong :s

```
def application do
    [
      applications: [
        ... :cqerl ...
      ]
    ]
  end
```

**Comment by sebastian-nanek** [comment]
@schlan Thanks!
