### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by hopewise** [matehat/cqex#9]
I have just installed Cassandra 3.7, I tried to connect:

```
{:ok, client} = :cqerl.new_client({{x,x,x,x},9042},[{:auth, {:cqerl_auth_plain_handler, [{"user_name", "password"}]}}])
```

but I got this error:

> *\* (exit) exited in: :gen_server.call(:cqerl, {:get_client, {{x,x,x,x}, 9042}, [auth: {:cqerl_auth_plain_handler, [{"user_name", "password"}]}]})
>     *\* (EXIT) time out
>     (stdlib) gen_server.erl:204: :gen_server.call/2

Any advice?

**Comment by matehat** [comment]
Did you get this working? Seems to be a connection configuration issue

**Comment by matehat** [comment]
@hopewise did you get it working?
